/// Central fact table at one row per synthetic patient encounter (visit). Holds foreign keys to Date, Patient, Provider, Department (a department at a specific facility), Payer, Diagnosis, Encounter Type, and Discharge Disposition, plus length of stay, allowed amount, and a readmission flag. Rows are generated with weighted random distributions from a fixed seed, so results are reproducible across refreshes: Outpatient is the most common encounter type (~42%); department, facility type, and diagnosis depend on encounter type and department; pediatric patients are seen only by the Pediatrics department (and also by Family Medicine and Emergency Medicine); patients 65 and over are mostly Medicare; volume grows each year, peaks in winter, and scheduled care is lighter on weekends; some providers, patients, and facilities are much busier than others. Row volume is controlled by the Encounter Row Count Power Query parameter. Use measures in _Measures rather than columns here for numeric analysis.
table Encounters
	lineageTag: 82f9b47a-3fb9-4ccc-b952-28f46674e505

	/// Foreign key (YYYYMMDD) linking each encounter to the Date dimension by service date.
	column 'Date Key'
		dataType: int64
		isHidden
		lineageTag: 0b0a244c-ae34-488c-9178-035516637cec
		summarizeBy: none
		sourceColumn: Date Key

	/// Foreign key linking each encounter to the Patient dimension. Used by the # Patients distinct-count measure.
	column 'Patient Key'
		dataType: int64
		isHidden
		lineageTag: 2578a6f6-bb55-40a3-a898-3156215b9cb8
		summarizeBy: none
		sourceColumn: Patient Key

	/// Foreign key linking each encounter to the rendering Provider dimension.
	column 'Provider Key'
		dataType: int64
		isHidden
		lineageTag: 1a7c9abe-855f-4fc5-8128-ccda2b677bd6
		summarizeBy: none
		sourceColumn: Provider Key

	/// Foreign key linking each encounter to the Payer dimension.
	column 'Payer Key'
		dataType: int64
		isHidden
		lineageTag: 7c534814-e9b8-4746-86e7-353f73fb9e73
		summarizeBy: none
		sourceColumn: Payer Key

	/// Foreign key linking each encounter to its primary Diagnosis.
	column 'Diagnosis Key'
		dataType: int64
		isHidden
		lineageTag: 7abe1e7b-8703-485e-9afd-7f5ef7bb365a
		summarizeBy: none
		sourceColumn: Diagnosis Key

	/// Foreign key linking each encounter to the Encounter Type dimension.
	column 'Encounter Type Key'
		dataType: int64
		isHidden
		lineageTag: a3972d5b-c808-4dfe-9150-2894e31c4adf
		summarizeBy: none
		sourceColumn: Encounter Type Key

	/// Foreign key linking each encounter to the Discharge Disposition dimension.
	column 'Discharge Disposition Key'
		dataType: int64
		isHidden
		lineageTag: a1c4dafc-b98a-4caf-b820-84cd7b7f8d8c
		summarizeBy: none
		sourceColumn: Discharge Disposition Key

	/// Number of days the patient stayed. Inpatient stays follow a right-skewed distribution from 1 to 30 days (average about 4); Observation stays are 1 to 3 days; all other encounter types are zero. Hidden; use Total Length of Stay Days or Average Length of Stay Days measures.
	column 'Length of Stay Days'
		dataType: int64
		isHidden
		lineageTag: 1d4b40c5-37e4-4fe9-9353-386233f8a720
		summarizeBy: sum
		sourceColumn: Length of Stay Days

	/// Synthetic allowed amount in US dollars: the reimbursable amount accepted for the encounter under the payer contract (combined payer and patient responsibility). Driven by encounter type (inpatient stays scale with length of stay), department (for example Oncology and Cardiology cost more), payer type (Commercial pays most, Self-Pay and Medicaid least), plus random variation. Hidden; use Total Allowed Amount or Average Allowed Amount per Encounter measures.
	column 'Allowed Amount'
		dataType: decimal
		isHidden
		formatString: $#,0.00;($#,0.00);$0.00
		lineageTag: c44ace7a-474b-44c2-bcd0-6c657119e067
		summarizeBy: sum
		sourceColumn: Allowed Amount

	/// Yes when the encounter is classified as a readmission, otherwise No. Probability depends on encounter type (about 14% for Inpatient, 9% Observation, 6% Emergency, 1-3% for other types) and is higher for patients 65 and over. Synthetic demonstration flag; not a CMS 30-day all-cause readmission calculation. Use # Readmission Encounters or Readmission Rate (%) for metrics.
	column 'Readmission Flag'
		dataType: string
		lineageTag: 5c4e36ab-5160-41a1-b650-a254bfa0d45d
		sourceColumn: Readmission Flag

	/// Foreign key linking each encounter to the Department dimension: the department of the rendering provider at the facility where care was delivered, calculated as (facility number - 1) x 10 + department position. Row-level security on Department filters Encounters through this key.
	column 'Department Key'
		dataType: int64
		isHidden
		lineageTag: 58d31635-bce0-4451-bcc5-14c095a4c4fb
		summarizeBy: none
		sourceColumn: Department Key

	partition Encounters = m
		mode: import
		source =
				let
				    RequestedCount = Number.From(#"Encounter Row Count"),
				    EncounterCount = if RequestedCount < 1 or Number.Mod(RequestedCount, 1) <> 0 then error "Encounter Row Count must be a positive whole number." else Int64.From(RequestedCount),
				    PatientCount = List.Max({1, Number.RoundUp(EncounterCount / 100)}),
				    EndDate = #date(2026, 12, 31),
				
				    // Weighted random helpers: each weight list becomes a 10,000-bucket lookup (0.01% resolution) built once,
				    // so every pick is a single positional lookup instead of building a temporary list per row
				    Buckets = 10000,
				    Cum = (weights as list) as list =>
				        let
				            total = List.Sum(weights),
				            cumulative = List.Skip(List.Accumulate(weights, {0}, (state, w) => state & {List.Last(state) + w / total}), 1),
				            last = List.Count(weights) - 1
				        in
				            List.Buffer(List.Transform(List.Numbers(0, Buckets), (b) => List.Min({List.Count(List.Select(cumulative, (c) => c <= (b + 0.5) / Buckets)), last}))),
				    Pick = (r as number, lookup as list) as number => lookup{Number.RoundDown(r * Buckets)},
				    // Skews selection toward lower indexes so some providers, patients, and facilities are busier than others
				    Skew = (r as number, n as number, power as number) as number =>
				        List.Min({Number.RoundDown(n * Number.Power(r, power)), n - 1}),
				
				    // Rows are generated in fixed-size chunks; each chunk buffers only its own random values (ChunkSize * K numbers)
				    // and is streamed to the engine before the next chunk is created, so memory stays flat regardless of row count.
				    // Each chunk uses its own fixed seed, so output is reproducible and the first N rows are identical for any larger count.
				    K = 20,
				    ChunkSize = 50000,
				    ChunkCount = Number.RoundUp(EncounterCount / ChunkSize),
				    BaseSeed = 20261002,
				
				    // Patient age bands: seed and weights must match the Patient query
				    AgeCum = Cum({18, 18, 17, 20, 14, 13}),
				    AgeIdx = List.Buffer(List.Transform(List.Random(PatientCount, 4242), (r) => Pick(r, AgeCum))),
				    AllKeys = List.Buffer(List.Numbers(1, PatientCount)),
				    PedKeysRaw = List.Select(AllKeys, (k) => AgeIdx{k - 1} = 0),
				    AdultKeysRaw = List.Select(AllKeys, (k) => AgeIdx{k - 1} > 0),
				    PedKeys = List.Buffer(if List.IsEmpty(PedKeysRaw) then AllKeys else PedKeysRaw),
				    AdultKeys = List.Buffer(if List.IsEmpty(AdultKeysRaw) then AllKeys else AdultKeysRaw),
				    PedCount = List.Count(PedKeys),
				    AdultCount = List.Count(AdultKeys),
				
				    YearCum = Cum({18, 19, 20, 21, 22}),
				    MonthCum = Cum({115, 110, 105, 95, 95, 90, 85, 90, 100, 105, 105, 110}),
				    // Encounter Type keys: 1 Inpatient, 2 Emergency, 3 Observation, 4 Outpatient, 5 Ambulatory Surgery, 6 Urgent Care, 7 Telehealth, 8 Home Health
				    TypeCum = Cum({7, 13, 4, 42, 6, 10, 14, 4}),
				    // Department keys: 1 Cardiology, 2 Emergency Medicine, 3 Family Medicine, 4 Gastroenterology, 5 General Surgery, 6 Internal Medicine, 7 Neurology, 8 Oncology, 9 Orthopedics, 10 Pediatrics
				    DefaultDept = {10, 0, 24, 6, 3, 20, 6, 8, 9, 14},
				    DeptCumByType = List.Buffer(List.Transform({
				        {18, 0, 2, 8, 14, 25, 8, 10, 10, 5},
				        {0, 88, 0, 0, 0, 4, 0, 0, 4, 4},
				        {30, 15, 0, 10, 0, 30, 10, 0, 0, 5},
				        DefaultDept,
				        {0, 0, 0, 20, 40, 0, 0, 5, 35, 0},
				        {0, 20, 60, 0, 0, 5, 0, 0, 0, 15},
				        DefaultDept,
				        DefaultDept
				    }, Cum)),
				    // Facility type index: 0 Academic Medical Center, 1 Community Hospital, 2 Ambulatory Surgery Center, 3 Outpatient Clinic, 4 Urgent Care Center
				    FacilityCumByType = List.Buffer(List.Transform({
				        {45, 55, 0, 0, 0},
				        {35, 65, 0, 0, 0},
				        {40, 60, 0, 0, 0},
				        {25, 10, 0, 65, 0},
				        {20, 20, 60, 0, 0},
				        {0, 0, 0, 10, 90},
				        {30, 0, 0, 70, 0},
				        {0, 50, 0, 50, 0}
				    }, Cum)),
				    // Payer type index: 0 Commercial, 1 Medicaid, 2 Medicare, 3 Self-Pay, 4 Other Government
				    PayerCumPediatric = Cum({55, 40, 0, 2, 3}),
				    PayerCumAdult = Cum({62, 20, 3, 8, 7}),
				    PayerCumSenior = Cum({8, 4, 82, 2, 4}),
				    PlanCum = Cum({45, 30, 15, 10}),
				    // Clinical category index: Cardiovascular, Digestive, Endocrine, Infectious Disease, Injury, Mental Health, Musculoskeletal, Neurological, Oncology, Respiratory
				    DiagCumByDept = List.Buffer(List.Transform({
				        {75, 2, 10, 1, 1, 2, 1, 2, 1, 5},
				        {12, 8, 3, 10, 30, 6, 8, 6, 1, 16},
				        {12, 8, 15, 12, 5, 14, 12, 5, 2, 15},
				        {2, 80, 5, 5, 1, 2, 1, 1, 3, 0},
				        {5, 40, 3, 5, 20, 0, 10, 0, 17, 0},
				        {18, 8, 20, 10, 3, 8, 8, 5, 5, 15},
				        {5, 1, 3, 1, 5, 15, 5, 65, 0, 0},
				        {2, 3, 2, 3, 0, 2, 1, 2, 85, 0},
				        {0, 0, 2, 1, 30, 0, 67, 0, 0, 0},
				        {2, 8, 5, 25, 12, 10, 6, 4, 1, 27}
				    }, Cum)),
				    // Discharge Disposition keys: 1 Home or Self Care, 2 Skilled Nursing Facility, 3 Home Health Service, 4 Transferred to Acute Care, 5 Against Medical Advice, 6 Expired
				    RoutineDischarge = {99, 0, 0.3, 0.5, 0.15, 0.05},
				    DischargeCumByType = List.Buffer(List.Transform({
				        {72, 11, 10, 3, 2, 2},
				        {94, 0.5, 0.5, 3, 1.8, 0.2},
				        {90, 3, 4, 2, 1, 0},
				        RoutineDischarge, RoutineDischarge, RoutineDischarge, RoutineDischarge, RoutineDischarge
				    }, Cum)),
				    ObservationLosCum = Cum({60, 35, 5}),
				    BaseAmount = {9500, 1650, 3800, 240, 5600, 175, 95, 310},
				    DeptFactor = {1.3, 1.0, 1.0, 1.1, 1.25, 1.0, 1.15, 1.6, 1.2, 0.9},
				    PayerFactor = {1.3, 0.7, 1.0, 0.55, 0.85},
				    ReadmitRate = {0.14, 0.06, 0.09, 0.015, 0.02, 0.01, 0.01, 0.03},
				
				    // Builds one encounter as a positional list (lighter than a record); R(slot) returns this row's random value for a slot
				    MakeRow = (R as function) as list =>
				        let
				            TypeKey = Pick(R(4), TypeCum) + 1,
				            Year = 2022 + Pick(R(0), YearCum),
				            Month = Pick(R(1), MonthCum) + 1,
				            DaysInMonth = Date.DaysInMonth(#date(Year, Month, 1)),
				            RawDate = #date(Year, Month, List.Min({Number.RoundDown(R(2) * DaysInMonth) + 1, DaysInMonth})),
				            DayIdx = Date.DayOfWeek(RawDate, Day.Monday),
				            // Scheduled care (outpatient, surgery, telehealth, home health) is mostly moved off weekends to a random following weekday
				            IsScheduledCare = List.Contains({4, 5, 7, 8}, TypeKey),
				            Shifted = if IsScheduledCare and DayIdx >= 5 and R(3) < 0.7 then Date.AddDays(RawDate, 7 - DayIdx + Number.RoundDown(R(3) / 0.7 * 5)) else RawDate,
				            ServiceDate = if Shifted > EndDate then RawDate else Shifted,
				            DeptKey = Pick(R(5), DeptCumByType{TypeKey - 1}) + 1,
				            ProviderKey = DeptKey + 10 * Skew(R(6), 500, 1.3),
				            PatientKey =
				                if DeptKey = 10 then PedKeys{Skew(R(7), PedCount, 1.2)}
				                else if DeptKey = 2 or DeptKey = 3 then AllKeys{Skew(R(7), PatientCount, 1.2)}
				                else AdultKeys{Skew(R(7), AdultCount, 1.2)},
				            AgeBand = AgeIdx{PatientKey - 1},
				            PayerType = Pick(R(8), if AgeBand = 0 then PayerCumPediatric else if AgeBand >= 4 then PayerCumSenior else PayerCumAdult),
				            FacilityType = Pick(R(10), FacilityCumByType{TypeKey - 1}),
				            LengthOfStay = if TypeKey = 1 then List.Min({1 + Number.RoundDown(-Number.Ln(1 - R(15)) * 3.6), 30}) else if TypeKey = 3 then Pick(R(15), ObservationLosCum) + 1 else 0,
				            Noise = Number.Exp((R(16) + R(17) + R(18) - 1.5) * 0.9),
				            Base = BaseAmount{TypeKey - 1} + (if TypeKey = 1 then 2600 * LengthOfStay else 0),
				            ReadmitProbability = ReadmitRate{TypeKey - 1} * (if AgeBand >= 4 then 1.3 else 1)
				        in
				            {
				                Date.Year(ServiceDate) * 10000 + Date.Month(ServiceDate) * 100 + Date.Day(ServiceDate),
				                PatientKey,
				                ProviderKey,
				                // Department-at-facility key: (facility number - 1) * 10 + department position
				                (FacilityType + 5 * Skew(R(11), 50, 1.4)) * 10 + DeptKey,
				                PayerType + 1 + 5 * Pick(R(9), PlanCum),
				                Pick(R(12), DiagCumByDept{DeptKey - 1}) + 1 + 10 * Skew(R(13), 10, 1.8),
				                TypeKey,
				                Pick(R(14), DischargeCumByType{TypeKey - 1}) + 1,
				                LengthOfStay,
				                Number.Round(Base * DeptFactor{DeptKey - 1} * PayerFactor{PayerType} * Noise, 2),
				                if R(19) < ReadmitProbability then "Yes" else "No"
				            },
				
				    MakeChunkRows = (chunk as number) as list =>
				        let
				            RowsInChunk = List.Min({ChunkSize, EncounterCount - chunk * ChunkSize}),
				            Rand = List.Buffer(List.Random(RowsInChunk * K, BaseSeed + chunk))
				        in
				            List.Transform(List.Numbers(0, RowsInChunk), (i) => MakeRow((slot) => Rand{i * K + slot})),
				
				    EncounterType = type table [
				        #"Date Key" = Int64.Type, #"Patient Key" = Int64.Type, #"Provider Key" = Int64.Type, #"Department Key" = Int64.Type,
				        #"Payer Key" = Int64.Type, #"Diagnosis Key" = Int64.Type, #"Encounter Type Key" = Int64.Type,
				        #"Discharge Disposition Key" = Int64.Type, #"Length of Stay Days" = Int64.Type, #"Allowed Amount" = Currency.Type, #"Readmission Flag" = text
				    ],
				    // Typed directly at creation: no Table.TransformColumnTypes pass over every cell
				    Result = Table.FromRows(List.Combine(List.Transform(List.Numbers(0, ChunkCount), MakeChunkRows)), EncounterType)
				in
				    Result

	annotation PBI_ResultType = Table

