/// Fourth row-level security (RLS) mapping design: one row per user (2,006 rows) combining a pipe-delimited list of department-at-facility keys with an All Access override flag. All-access users (executive and enterprise analysts) have All Access = TRUE and a blank key list; everyone else has All Access = FALSE and their keys, for example 11|12|13. Built for the RLS design benchmark from the same generated grants as the other security tables. No role in the model uses it to filter data (a Department-level role cannot coexist with the two-way security relationship); the Department Access role restricts it to the signed-in user's own row. Hidden; not for reporting.
table 'User Department Access (Delimited Override)'
	lineageTag: 09f1fdb5-00e8-4796-ac57-f76508fcf18e

	/// User principal name (UPN, typically the sign-in email address). One row per user; matched case-insensitively against USERPRINCIPALNAME().
	column 'User Email'
		dataType: string
		lineageTag: 1de2a3a4-8a86-4270-ad5d-0b31fba605fa
		summarizeBy: none
		sourceColumn: User Email

		changedProperty = IsHidden

	/// Pipe-delimited list of Department Key values (department at a facility, 1 to 2,500) the user may see, sorted ascending. Blank for all-access users, whose access comes from the All Access flag.
	column 'Department Keys'
		dataType: string
		lineageTag: ae3b835e-41a7-4414-bb0b-9f1ba8c25ec4
		summarizeBy: none
		sourceColumn: Department Keys

		changedProperty = IsHidden

	/// All-access override flag. TRUE grants every department at every facility, including ones added later, without listing keys. FALSE means access is limited to Department Keys.
	column 'All Access'
		dataType: boolean
		lineageTag: 9e281869-449e-491f-a945-3d8d41a501ce
		summarizeBy: none
		sourceColumn: All Access

		changedProperty = IsHidden

	partition 'User Department Access (Delimited Override)' = m
		mode: import
		source =
				let
				    FacilityCount = 250,
				    DepartmentCount = 10,
				    // Department Key = (Facility Number - 1) * 10 + department position (1 Cardiology ... 10 Pediatrics); matches the Department query
				    Key = (f as number, d as number) as number => (f - 1) * DepartmentCount + d,
				    AllFacilities = List.Numbers(1, FacilityCount),
				    AllKeys = List.Numbers(1, FacilityCount * DepartmentCount),
				    StateOf = (f as number) as number => Number.Mod(Number.IntegerDivide(f - 1, 5), 10),
				    FacilitiesInState = (s as number) as list => List.Select(AllFacilities, (f) => StateOf(f) = s),
				    DeptAcross = (depts as list, facilities as list) as list =>
				        List.Sort(List.Combine(List.Transform(facilities, (f) => List.Transform(depts, (d) => Key(f, d))))),
				    // Sample users referenced by the RLS Test report page
				    SampleUsers = {
				        {"executive@contoso.com", "All", AllKeys},
				        {"cardiology.manager@contoso.com", "Department", DeptAcross({1}, AllFacilities)},
				        {"usera@MngEnvMCAP249728.onmicrosoft.com", "Department", DeptAcross({1}, AllFacilities)},
				        {"ed.director@contoso.com", "Department", DeptAcross({2}, AllFacilities)},
				        {"primarycare.director@contoso.com", "Department", DeptAcross({3, 6, 10}, AllFacilities)},
				        {"surgery.director@contoso.com", "Department", DeptAcross({5, 9}, AllFacilities)},
				        {"specialty.analyst@contoso.com", "Department", DeptAcross({1, 4, 7, 8}, AllFacilities)}
				    },
				    // Generated users: 60% facility directors (10 keys), 20% department managers in one state (25 keys),
				    // 17.5% regional leaders for one state (250 keys), 2.5% enterprise analysts (all 2,500 keys / all-access)
				    GeneratedUserCount = 2000,
				    GeneratedUser = (u as number) as list =>
				        let
				            Slot = Number.Mod(u, 40),
				            Id = Text.PadStart(Text.From(u), 4, "0")
				        in
				            if Slot < 24 then {"facility.director." & Id & "@contoso.com", "Facility", DeptAcross(List.Numbers(1, DepartmentCount), {Number.Mod(u * 7, FacilityCount) + 1})}
				            else if Slot < 32 then {"department.manager." & Id & "@contoso.com", "Department", DeptAcross({Number.Mod(u, DepartmentCount) + 1}, FacilitiesInState(Number.Mod(Number.IntegerDivide(u, 10), 10)))}
				            else if Slot < 39 then {"regional.leader." & Id & "@contoso.com", "Region", DeptAcross(List.Numbers(1, DepartmentCount), FacilitiesInState(Number.Mod(u, 10)))}
				            else {"enterprise.analyst." & Id & "@contoso.com", "All", AllKeys},
				    Users = SampleUsers & List.Transform(List.Numbers(1, GeneratedUserCount), GeneratedUser),
				    // All-access users get a single row with the flag set and no key list; everyone else gets their pipe-delimited keys
				    Result = Table.FromRows(
				        List.Transform(Users, (x) => if x{1} = "All" then {x{0}, null, true} else {x{0}, Text.Combine(List.Transform(x{2}, Text.From), "|"), false}),
				        type table [#"User Email" = text, #"Department Keys" = nullable text, #"All Access" = logical])
				in
				    Result

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

