/// Synthetic patient dimension at one row per patient. Provides privacy-safe demographic attributes (age band, sex, race and ethnicity, state of residence) assigned by weighted random distributions from a fixed seed, and a patient cohort grouping for utilization analysis. Contains no names, medical record numbers, birth dates, or other direct identifiers. Row count scales with Encounter Row Count at one patient per 100 encounters; utilization is uneven, so some patients have many more encounters than others.
table Patient
	lineageTag: 533d2dab-de15-4f49-a0ff-9aee4d95368f

	/// Synthetic patient surrogate key used only for the relationship to Encounters. It is not a medical record number or real-world identifier. Use the # Patients measure to count patients.
	column 'Patient Key'
		dataType: int64
		isHidden
		isUnique
		lineageTag: 2c7b138c-fb67-415e-b7be-2996fb829526
		summarizeBy: none
		sourceColumn: Patient Key

	/// Patient age grouping: 0-17 (pediatric), 18-34, 35-49, 50-64, 65-74, and 75+. Use for age-based utilization comparisons; 65 and over typically aligns with Medicare eligibility.
	column 'Age Band'
		dataType: string
		lineageTag: ad80afd8-19cc-4d10-876c-2f16a7a2bd46
		sourceColumn: Age Band

	/// Patient sex category: Female, Male, or Unknown when unavailable or unspecified. Also referred to as gender in many questions.
	column Sex
		dataType: string
		lineageTag: 828e209f-48e5-4268-9205-f0f190649979
		sourceColumn: Sex

	/// Combined race and ethnicity category (Asian, Black or African American, Hispanic or Latino, White, Other, Unknown) for health-equity and disparity analysis. Values are synthetic.
	column 'Race and Ethnicity'
		dataType: string
		lineageTag: 547b8d94-dee6-40a9-bc80-25d6c914c5b8
		sourceColumn: Race and Ethnicity

	/// U.S. state of the patient's residence. Use for patient geography; for where care was delivered use Facility State instead.
	column 'Patient State'
		dataType: string
		lineageTag: 01a639c3-442b-44dd-bc64-be6f2477603e
		dataCategory: StateOrProvince
		sourceColumn: Patient State

	/// Stable grouping (Cohort 001 through Cohort 100) that segments patients for population comparisons without exposing patient-level identifiers.
	column 'Patient Cohort'
		dataType: string
		lineageTag: c2fa4278-82d9-4550-9c68-850684684e09
		isDefaultLabel
		sourceColumn: Patient Cohort

	partition Patient = m
		mode: import
		source =
				let
				    PatientCount = List.Max({1, Number.RoundUp(Number.From(#"Encounter Row Count") / 100)}),
				
				    // Weighted random helpers: identical to the Encounters query (10,000-bucket lookups) so age bands match exactly
				    Buckets = 10000,
				    Cum = (weights as list) as list =>
				        let
				            total = List.Sum(weights),
				            cumulative = List.Skip(List.Accumulate(weights, {0}, (state, w) => state & {List.Last(state) + w / total}), 1),
				            last = List.Count(weights) - 1
				        in
				            List.Buffer(List.Transform(List.Numbers(0, Buckets), (b) => List.Min({List.Count(List.Select(cumulative, (c) => c <= (b + 0.5) / Buckets)), last}))),
				    Pick = (r as number, lookup as list) as number => lookup{Number.RoundDown(r * Buckets)},
				
				    // Age band seed and weights must stay identical to the Encounters query (used to route pediatric and Medicare patients)
				    AgeBands = {"0-17", "18-34", "35-49", "50-64", "65-74", "75+"},
				    AgeCum = Cum({18, 18, 17, 20, 14, 13}),
				    Sexes = {"Female", "Male", "Unknown"},
				    SexCum = Cum({52, 47, 1}),
				    Races = {"White", "Hispanic or Latino", "Black or African American", "Asian", "Other", "Unknown"},
				    RaceCum = Cum({58, 18, 13, 6, 3, 2}),
				    States = {"California", "Texas", "Florida", "New York", "Illinois", "Ohio", "Washington", "Arizona", "Minnesota", "Massachusetts"},
				    StateCum = Cum({18, 14, 12, 11, 8, 7, 7, 7, 8, 8}),
				
				    AgeRand = List.Buffer(List.Random(PatientCount, 4242)),
				    SexRand = List.Buffer(List.Random(PatientCount, 4243)),
				    RaceRand = List.Buffer(List.Random(PatientCount, 4244)),
				    StateRand = List.Buffer(List.Random(PatientCount, 4245)),
				
				    Rows = List.Transform(List.Numbers(1, PatientCount), (k) => {
				        k,
				        AgeBands{Pick(AgeRand{k - 1}, AgeCum)},
				        Sexes{Pick(SexRand{k - 1}, SexCum)},
				        Races{Pick(RaceRand{k - 1}, RaceCum)},
				        States{Pick(StateRand{k - 1}, StateCum)},
				        "Cohort " & Text.PadStart(Text.From(Number.Mod(k - 1, 100) + 1), 3, "0")
				    }),
				    // Typed directly at creation: no Table.TransformColumnTypes pass over every cell
				    Result = Table.FromRows(Rows, type table [
				        #"Patient Key" = Int64.Type, #"Age Band" = text, Sex = text, #"Race and Ethnicity" = text, #"Patient State" = text, #"Patient Cohort" = text
				    ])
				in
				    Result

	annotation PBI_ResultType = Table

