/// Row-level security (RLS) bridge table at one row per user per department-at-facility key the user may access (about 240,000 rows for 2,006 users). Related many-to-one to Department on Granted Department Key with cross-filtering and security filtering in both directions. The Department Access role filters this table to User Email = USERPRINCIPALNAME(); the remaining rows then filter Department, and through it Encounters, to the user's granted departments. Users with no rows see no data. Hidden; not for reporting.
table 'User Department Access'
	lineageTag: db6fe5af-e0bc-49be-b3c6-28e0293e8f1d

	/// User principal name (UPN, typically the sign-in email address) of a person granted access. Compared against USERPRINCIPALNAME() by the Department Access row-level security role; matching is case-insensitive. Includes 6 named sample users plus 2,000 generated users (facility directors, department managers, regional leaders, enterprise analysts).
	column 'User Email'
		dataType: string
		lineageTag: db4f8f00-1d4a-4a96-8444-3d6a54357949
		summarizeBy: none
		sourceColumn: User Email

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Department Key (department at a facility, 1 to 2,500) that the user may see. One row per user per granted key; an enterprise user with access to everything has 2,500 rows.
	column 'Granted Department Key'
		dataType: int64
		lineageTag: c4ab3f2c-e529-4e0a-9821-58722d8f329b
		summarizeBy: none
		sourceColumn: Granted Department Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'User Department Access' = m
		mode: import
		source =
				let
				    FacilityCount = 250,
				    DepartmentCount = 10,
				    // Department Key = (Facility Number - 1) * 10 + department position (1 Cardiology ... 10 Pediatrics); matches the Department query
				    Key = (f as number, d as number) as number => (f - 1) * DepartmentCount + d,
				    AllFacilities = List.Numbers(1, FacilityCount),
				    AllKeys = List.Numbers(1, FacilityCount * DepartmentCount),
				    StateOf = (f as number) as number => Number.Mod(Number.IntegerDivide(f - 1, 5), 10),
				    FacilitiesInState = (s as number) as list => List.Select(AllFacilities, (f) => StateOf(f) = s),
				    DeptAcross = (depts as list, facilities as list) as list =>
				        List.Sort(List.Combine(List.Transform(facilities, (f) => List.Transform(depts, (d) => Key(f, d))))),
				    // Sample users referenced by the RLS Test report page
				    SampleUsers = {
				        {"executive@contoso.com", "All", AllKeys},
				        {"cardiology.manager@contoso.com", "Department", DeptAcross({1}, AllFacilities)},
				        {"ed.director@contoso.com", "Department", DeptAcross({2}, AllFacilities)},
				        {"primarycare.director@contoso.com", "Department", DeptAcross({3, 6, 10}, AllFacilities)},
				        {"surgery.director@contoso.com", "Department", DeptAcross({5, 9}, AllFacilities)},
				        {"specialty.analyst@contoso.com", "Department", DeptAcross({1, 4, 7, 8}, AllFacilities)}
				    },
				    // Generated users: 60% facility directors (10 keys), 20% department managers in one state (25 keys),
				    // 17.5% regional leaders for one state (250 keys), 2.5% enterprise analysts (all 2,500 keys / all-access)
				    GeneratedUserCount = 2000,
				    GeneratedUser = (u as number) as list =>
				        let
				            Slot = Number.Mod(u, 40),
				            Id = Text.PadStart(Text.From(u), 4, "0")
				        in
				            if Slot < 24 then {"facility.director." & Id & "@contoso.com", "Facility", DeptAcross(List.Numbers(1, DepartmentCount), {Number.Mod(u * 7, FacilityCount) + 1})}
				            else if Slot < 32 then {"department.manager." & Id & "@contoso.com", "Department", DeptAcross({Number.Mod(u, DepartmentCount) + 1}, FacilitiesInState(Number.Mod(Number.IntegerDivide(u, 10), 10)))}
				            else if Slot < 39 then {"regional.leader." & Id & "@contoso.com", "Region", DeptAcross(List.Numbers(1, DepartmentCount), FacilitiesInState(Number.Mod(u, 10)))}
				            else {"enterprise.analyst." & Id & "@contoso.com", "All", AllKeys},
				    Users = SampleUsers & List.Transform(List.Numbers(1, GeneratedUserCount), GeneratedUser),
				    Rows = List.Combine(List.Transform(Users, (x) => List.Transform(x{2}, (k) => {x{0}, k}))),
				    Result = Table.FromRows(Rows, type table [#"User Email" = text, #"Granted Department Key" = Int64.Type])
				in
				    Result

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

